name = "meme-manager-d1-worker"
main = "src/index.ts"
compatibility_date = "2026-02-28"

[[d1_databases]]
binding = "DB"
database_name = "meme-manager-db"
# 部署后用 `wrangler d1 create meme-manager-db` 创建数据库，将返回的 database_id 填入下方
database_id = "3ab9f513-a5d7-46cc-af47-d472e4c89255"
